version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install Flask==2.3.3 Flask-SQLAlchemy==3.1.1 Flask-Login==0.6.2 Flask-WTF==1.2.1 Werkzeug==2.3.7 email-validator==2.0.0 python-dotenv==1.0.0
     
  build:
    commands:
    
artifacts:
  files:
    - '**/*'
